name: Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Run once a day at 12 PM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Configure Git
      run: |
        git config --global user.name 'iamr7d'
        git config --global user.email 'rahulrajpvr7d.here@gmail.com'
        
    - name: Make pattern commits
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Pattern for "r7d" (1 represents commit, 0 represents no commit)
        # This creates a 7x15 grid pattern for "r7d"
        PATTERN=(
          "0 0 1 1 1 0 0 0 1 1 1 0 0 1 1"
          "0 1 1 0 0 1 0 1 1 0 0 1 0 1 1"
          "0 1 1 0 0 0 0 1 1 0 0 1 0 1 1"
          "0 1 1 1 1 0 0 1 1 1 1 1 0 1 1"
          "0 1 1 0 1 0 0 1 1 0 0 1 0 1 1"
          "0 1 1 0 0 1 0 1 1 0 0 1 0 1 1"
          "0 1 1 0 0 1 0 1 1 0 0 1 0 0 1"
        )
        
        # Get current date
        CURRENT_DATE=$(date '+%Y-%m-%d')
        
        # Get day of week (0-6, 0 is Sunday)
        DAY_OF_WEEK=$(date +%w)
        
        # Get the row in our pattern (0-6)
        ROW=$DAY_OF_WEEK
        
        # Read the pattern for today's row
        IFS=' ' read -ra TODAY_PATTERN <<< "${PATTERN[$ROW]}"
        
        # Loop through each position in today's pattern
        for ((i=0; i<${#TODAY_PATTERN[@]}; i++)); do
          if [ "${TODAY_PATTERN[$i]}" = "1" ]; then
            # Make multiple commits for this position
            NUM_COMMITS=$((RANDOM % 3 + 1))  # 1-3 commits
            
            for ((j=0; j<$NUM_COMMITS; j++)); do
              # Add timestamp to make each commit unique
              TIMESTAMP=$(date '+%H:%M:%S')
              echo "Commit at $TIMESTAMP" >> data.txt
              
              # Random delay between commits (1-60 seconds)
              sleep $((1 + RANDOM % 60))
              
              git add data.txt
              git commit -m "Pattern commit - $CURRENT_DATE $TIMESTAMP"
            done
          fi
        done
        
        # Push all commits using token
        git remote set-url origin "https://$PAT_TOKEN@github.com/iamr7d/behavellm.git"
        git push origin main
